Add: link to game
opentech-pe/ot-awesome-list pull request #3
Opened 2020-09-10 03:43 UTC by frida-luz

Add link of an educational game to learn Flexbox CSS

2020-09-11 22:08 UTC, paulotijero requested changes
Muchas gracias por tu contribución, dejo algunas observaciones.

2020-09-11 22:08 UTC, paulotijero commented on README.md
> - **[⬆ Volver Arriba](#tabla-de-contenido)**
Vuelva a agregar esta linea debajo del link que agrego.

2020-09-11 22:08 UTC, paulotijero commented on README.md
> +🇺🇸🍎👾 [FLEXBOX FROGGY. Educational game to learn css](https://flexboxfroggy.com/#es)
Pequeno cambio para mantener el formato de los links.
```suggestion
🇺🇸🍎👾 [Flexbox Froggy: Educational game to learn css](https://flexboxfroggy.com/#es)
```

2020-09-12 02:43 UTC, frida-luz reviewed
quedó listo

2020-09-12 02:43 UTC, frida-luz commented on README.md
> - **[⬆ Volver Arriba](#tabla-de-contenido)**
listo

2020-09-12 20:15 UTC, JimmyLoloy98 approved these changes
Gracias por contribuir con la comunidad :gem:

2020-09-13 03:55 UTC, paulotijero approved these changes

2020-09-13 03:56 UTC, merged